WebApplication2/ViewModels/ExternalLoginConfirmationViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.ViewModels
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

WebApplication2/ViewModels/ForgotPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.ViewModels
{
    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

    }
}

WebApplication2/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.ViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [Required]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Passwords Must Match!!!" )]
        public string ConfirmPassword { get; set; }
    }
}

WebApplication2/ViewModels/ResetPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.ViewModels
{
    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(60,ErrorMessage = "The Password must be between 6 and 60 characters long.",MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name="Confirm Password")]
        [Compare("Password",ErrorMessage = "The password and the confirmation password must match each other.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }
}

WebApplication2/Controllers/MainController.cs
using System.Security.Claims;
using System.Threading.Tasks;
using WebApplication2.Models;
using WebApplication2.Services;
using WebApplication2.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication2.Controllers
{
    public class MainController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSend _emailSend;
        private readonly ISmsSend _smsSend;

        public MainController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IEmailSend emailSend, ISmsSend smsSend)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSend = emailSend;
            _smsSend = smsSend;

        }
        public IActionResult Index()
        {
            return View();
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var loginResults =
                    await
                        _signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe,
                            lockoutOnFailure: false);
                if (loginResults.Succeeded)
                {
                    return Content(loginResults.Succeeded.ToString());
                    //return RedirectToAction("Index", "LoggedIn");

                }
                ModelState.AddModelError(string.Empty, "Invalid Login Information.");
                return View(model);
            }
            return View(model);
        }

        /*        [HttpPost]
                [Route("Main/Login")]
                public async Task<IActionResult> LoginApi([FromBody]LoginViewModel model)
                {
                    var loginResults = await _signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe,
                                lockoutOnFailure: false);
                    if (loginResults.Succeeded)
                    {

                        return Ok("True");
                    }
                    return BadRequest("False");

                } */

        [HttpPost]
        [Route("Main/Login")]
        public IActionResult LoginApi([FromBody]LoginViewModel model)  // default primitive types are 'property binded' from uri and complex from body. FromBody and FromUri for reverse.
        {
            var loginResults = _signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe,
                        lockoutOnFailure: false).Result;
            if (loginResults.Succeeded)
            {

                return Ok("True");
            }
            return BadRequest("False");

        }

        public IActionResult Register()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var identityUser = new ApplicationUser
                {
                    UserName = model.Username,
                    Email = model.Username

                };

                var identityResults = await _userManager.CreateAsync(identityUser, model.Password);
                if (identityResults.Succeeded)
                {

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(identityUser);

                    var callbackUrl = Url.Action("ConfirmEmail", "Main", new {userId = identityUser.Id, code },
                        protocol: HttpContext.Request.Scheme);
                    await
                        _emailSend.SendEmailAsync(model.Username, "Confirm Account",
                            $"Please Confirm your account by " +
                            $"clicking this link:<a href='{callbackUrl}'>Link</a>");

                    await _signInManager.SignInAsync(identityUser, isPersistent: false);
                    return View(model);
                    ;
                }
                else
                {

                    ModelState.AddModelError(string.Empty, "Error in Creating my User.");
                    return View(model);
                }

            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }

            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return View("Error");

            }

            var result = await _userManager.ConfirmEmailAsync(user,code);
            return View ("ConfirmEmail");

        }

        public IActionResult ResetPassword()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);

                if (user == null)
                {


                    return RedirectToAction("Index", "Main");
                }

                var result = await _userManager.ResetPasswordAsync(user,model.Code,model.Password);
                if (!result.Succeeded) return View(model);
                await _signInManager.SignInAsync(user, isPersistent: false);
                return RedirectToAction("Index", "LoggedIn");
            }

            return View(model);

        }

        public IActionResult ForgotPassword()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                var confirmed = await _userManager.IsEmailConfirmedAsync(user);
                if (user == null || !confirmed)
                {

                    return View("ForgotPasswordConfirmation");
                }
                // Send Email Confirmation

                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                var callbackUrl = Url.Action("ResetPassword", "Main", new { userId = user.Id, code },
                      protocol: HttpContext.Request.Scheme);
                await
                    _emailSend.SendEmailAsync(model.Email, "Reset Password",
                        $"Please Reset you Password by " +
                        $"clicking this link:<a href='{callbackUrl}'>Link</a>");


            }

            return View(model);

        }

        public IActionResult ForgotPasswordConfirmation()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {

            await _signInManager.SignOutAsync();

            return RedirectToAction("Index", "Main");
        }

        [HttpGet]
        public async Task<IActionResult> SmsTest()
        {

            await _smsSend.SendSmsAsync("14695027582", "This is a test Message");

            return RedirectToAction("Index", "Main");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            var redirectUrl = Url.Action("ExternalLoginCallback", "Main", new {returnUrl});

            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties,provider);

        }


        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                return View(nameof(ExternalLoginFailure));


            }

            var info = await _signInManager.GetExternalLoginInfoAsync();

            if (info == null)
            {
                return RedirectToAction(nameof(ExternalLoginFailure));

            }

            var result =
                await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false);

            if (result.Succeeded)
            {

                return Redirect(returnUrl);
            }
            else
            {

                ViewData["ReturnUrl"] = returnUrl;
                ViewData["LoginProvider"] = info.LoginProvider;
                var email = info.Principal.FindFirstValue(ClaimTypes.Email);
                return View("ExternalLoginConfirmation",
                    new ExternalLoginConfirmationViewModel {Email = email});
            }
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ExternalLoginConfirmation(ExternalLoginConfirmationViewModel model,
            string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                var info = await _signInManager.GetExternalLoginInfoAsync();
                if (info == null)
                {

                    return View("ExternalLoginFailure");

                }

                var user = new ApplicationUser {UserName = model.Email,Email = model.Email};

                var alreadyRegistered = await _userManager.FindByEmailAsync(model.Email);
                var result = await _userManager.CreateAsync(user);

WebApplication2/ViewComponents/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication2.ViewComponents
{
    public class LoginViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WebApplication2/Views/Main/ConfirmEmail.cshtml
@{
    ViewData["Title"] = "Confirm Email";
}
<h2 class="ui header">@ViewData["Title"]</h2>
<div>
    <p>
        Thank you for confirming your email. Please <a asp-controller="Main" asp-action="Index">Click here to Log in</a>.
    </p>
</div>

WebApplication2/Views/Main/ExternalLoginConfirmation.cshtml
@model ExternalLoginConfirmationViewModel
@{
    ViewData["Title"] = "Register";
}
<h2 class="ui header">@ViewData["Title"]</h2>
<h3 class="ui sub header">Associate your @ViewData["LoginProvider"] account</h3>
<form asp-controller="Main" asp-action="ExternalLoginConfirmation" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="ui small form validate-me" role="form">

    <p class="content">
        You've successfully authenticated with <strong>@ViewData["LoginProvider"]</strong>.
        Please enter a user name for this site below and click the Register button to finish
        logging in.
    </p>
    <div class="six wide field">
        <div class="ui left icon input">
            <i class="user icon"></i>
            <input asp-for="Email" placeholder="Email address" />
            <div asp-validation-for="LoginModel.Email"></div>
        </div>
    </div>
    <br />
    <input type="submit" class="ui large blue submit button" value="Register" />
    <br />
    <div asp-validation-summary="All" class="ui error message"></div>
</form>

WebApplication2/Views/Main/ExternalLoginFailure.cshtml
@{
    ViewData["Title"] = "Login Failure";
}
<h2 class="ui header">@ViewData["Title"]</h2>
<h3 class="ui sub header">Unsuccessful login with service.</h3>

WebApplication2/Views/Main/ForgotPassword.cshtml
@model ForgotPasswordViewModel
@{
    ViewData["Title"] = "Forgot Password";
}

<div class="ui raised very padded text container">
    <h2 class="ui header centered">Forgot Password</h2>
    <form asp-controller="Main" asp-action="ForgotPassword" class="ui large form validate-me" method="post">
        <div class="ui stacked segment">
            <div class="field">
                <div class="ui left icon input">
                    <i class="user icon"></i>
                    <input asp-for="Email" placeholder="Email Address" />

                </div>

            </div>

            <input type="submit" class="ui large black submit button" value="Send" />
            <div asp-validation-summary="All" class="ui error message"></div>

        </div>
        @Html.AntiForgeryToken()
    </form>


</div>

WebApplication2/Views/Main/ForgotPasswordConfirmation.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Forgot Password Confirmation";
}
<h1 class="ui header">@ViewData["Title"]</h1>

<p>
    Check Your Email To Reset Your Password.

</p>

WebApplication2/Views/Main/Index.cshtml
<core-app></core-app>
@await Component.InvokeAsync("Login")

WebApplication2/Views/Main/Register.cshtml
@model RegisterViewModel
@{
    ViewData["Title"] = "Register";
}

<div class="ui raised very padded text container">
    <h2 class="ui header centered">Register</h2>
    <form asp-controller="Main" asp-action="Register" class="ui large form validate-me" method="post">
        <div class="ui stacked segment">
            <div class="field">
                <div class="ui left icon input">
                    <i class="user icon"></i>
                    <input asp-for="Username" placeholder="Email Address"/>

                </div>

            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="lock icon"></i>
                    <input asp-for="Password" type="password" placeholder="Password" />

                </div>

            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="lock icon"></i>
                    <input asp-for="ConfirmPassword" type="password" placeholder="Confirm Password" />

                </div>

            </div>
            <input type="submit" class="ui large green submit button" value="Register"/>
            <div asp-validation-summary="All" style="color:red;"></div>

        </div>
        @Html.AntiForgeryToken()
    </form>


</div>

WebApplication2/Views/Main/ResetPassword.cshtml
@model ResetPasswordViewModel
@{
    ViewData["Title"] = "Reset Password";
}

<div class="ui raised very padded text container">
    <h2 class="ui header centered">Reset Password</h2>
    <form asp-controller="Main" asp-action="ResetPassword" class="ui large form validate-me" method="post">

        <input asp-for="Code" type="hidden" value="@Context.Request.Query["code"]" />
        <div class="ui stacked segment">
            <div class="field">
                <div class="ui left icon input">
                    <i class="user icon"></i>
                    <input asp-for="Email" placeholder="Email Address" />

                </div>

            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="lock icon"></i>
                    <input asp-for="Password" type="password" placeholder="Password" />

                </div>

            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="lock icon"></i>
                    <input asp-for="ConfirmPassword" type="password" placeholder="Confirm Password" />

                </div>

            </div>
            <input type="submit" class="ui large Red submit button" value="Reset" />
            <div asp-validation-summary="All" style="color: red;"></div>

        </div>
        @Html.AntiForgeryToken()
    </form>


</div>

WebApplication2/Views/Main/SmsTest.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}